/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as ProtectedImport } from './routes/_protected'
import { Route as IndexImport } from './routes/index'
import { Route as ProtectedHomeImport } from './routes/_protected/home'
import { Route as ProtectedStockIndexImport } from './routes/_protected/stock/index'
import { Route as ProtectedOrderIndexImport } from './routes/_protected/order/index'
import { Route as ProtectedCustomerIndexImport } from './routes/_protected/customer/index'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedRoute = ProtectedImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedHomeRoute = ProtectedHomeImport.update({
  path: '/home',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedStockIndexRoute = ProtectedStockIndexImport.update({
  path: '/stock/',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedOrderIndexRoute = ProtectedOrderIndexImport.update({
  path: '/order/',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedCustomerIndexRoute = ProtectedCustomerIndexImport.update({
  path: '/customer/',
  getParentRoute: () => ProtectedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_protected/home': {
      id: '/_protected/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof ProtectedHomeImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/customer/': {
      id: '/_protected/customer/'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof ProtectedCustomerIndexImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/order/': {
      id: '/_protected/order/'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof ProtectedOrderIndexImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/stock/': {
      id: '/_protected/stock/'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof ProtectedStockIndexImport
      parentRoute: typeof ProtectedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  ProtectedRoute: ProtectedRoute.addChildren({
    ProtectedHomeRoute,
    ProtectedCustomerIndexRoute,
    ProtectedOrderIndexRoute,
    ProtectedStockIndexRoute,
  }),
  LoginRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_protected",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_protected": {
      "filePath": "_protected.tsx",
      "children": [
        "/_protected/home",
        "/_protected/customer/",
        "/_protected/order/",
        "/_protected/stock/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_protected/home": {
      "filePath": "_protected/home.tsx",
      "parent": "/_protected"
    },
    "/_protected/customer/": {
      "filePath": "_protected/customer/index.tsx",
      "parent": "/_protected"
    },
    "/_protected/order/": {
      "filePath": "_protected/order/index.tsx",
      "parent": "/_protected"
    },
    "/_protected/stock/": {
      "filePath": "_protected/stock/index.tsx",
      "parent": "/_protected"
    }
  }
}
ROUTE_MANIFEST_END */
